### ISSUE TITLE
add_header is being overwritten by location blocks

### ISSUE THREAD

**Issue by patbaker82** [pothi/wordpress-nginx#18]
For what you've written for caching plugins, the / location would be evaluated first.  However, given that you have locations for assets and .php the LAST location to be executed will write the headers.  So , for example in example.com.conf, if you include any of the caching plugins you'll always see the header X-CACHE MISS.  Even though the locations are being executed the last location to be executed will add the headers.

Per http://nginx.org/en/docs/http/ngx_http_headers_module.html#add_header

> 

> There could be several add_header directives. These directives are inherited from the previous level if and only if there are no add_header directives defined on the current level.

**Comment by pothi** [comment]
Hi,

Thanks for creating a new issue.

Please forgive my ignorance. I could not understand what you are trying to say.

> for example in example.com.conf, if you include any of the caching plugins you'll always see the header X-CACHE MISS.

No. I use example.com.conf too with WP Super Cache as the caching plugin on my site https://www.tinywp.in . You would see "x-cache" "miss" header in it only when the cache is not filled. Once filled (after the first visit), you wouldn't see "x-cache" "miss". Instead, you'd see "x-cache" "hit".

Do you have a test site where I can see a different behavior to understand what you are trying to say?

**Comment by patbaker82** [comment]
I'm actually using WP Rocket.

Heres my observation.

I always see the MISS header, but none of the other headers in location /.  However, I know we're serving the cached instance because I can see the page source with the annotation.  Further I know the location / is being executed because I can do a return 404 and see the 404.  For whatever reason the headers are getting lost.

**Comment by patbaker82** [comment]
Heres another example.  I would never see the header foo bar here.  I think this is because, per the documentation, location definitions in nginx inherit headers of the parent, however, if you specify headers in a location header that executes it overwrites the parent. 

`    location ~* \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) { return 404; }

        # Mitigate https://httpoxy.org/ vulnerabilities
        fastcgi_param HTTP_PROXY "";

        include "fastcgi_params";
        fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
        fastcgi_index               index.php;
        fastcgi_pass                fpm;

        add_header "X-CACHE" "MISS";
    }
    include "globals/wp-rocket.conf";
    add_header foo bar;
`

**Comment by patbaker82** [comment]
ok I figured it out.  I needed to set

`map $scheme $https_suffix { default '-https'; https '-https'; }` in the common.conf

Thanks!
