### ISSUE TITLE
can you help me

### ISSUE THREAD

**Issue by noura-dev-yeh** [pothi/wordpress-nginx#27]
Hi,
First, i would like to thank you for your contribution, it amazes me how someone could put effort like this just to help noobies like me.
I followed your instructions but I can't get it to work. I'm getting "This site can’t be reached" when i try to access my domain.
below is the text I used in the mydomain.com.conf, my wordpress installation is not complete. 
Could you please help me?
`

  
    server {
    listen 80;
    listen [::]:80; # IPv6 support
    server_name mydomain.com; 
    index index.php; # default file to serve
    root /usr/share/nginx/html;
    access_log /var/log/nginx/example.com-access.log;
   
    error_log /var/log/nginx/mydomain.com-error.log;

    include "globals/restrictions.conf";
    include "globals/assets.conf";

    location ~* \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        if (!-f $document_root$fastcgi_script_name) { return 404; }

        fastcgi_param HTTP_PROXY "";

        include "fastcgi_params";
        fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
        fastcgi_index               index.php;
        fastcgi_pass                fpm;

        add_header "X-Cache" "MISS";  }}`

**Comment by pothi** [comment]
"This site can’t be reached" indicates that the request can't reach Nginx. Either Nginx wasn't running or it could be a firewall issue. I may be wrong.

**Comment by noura-dev-yeh** [comment]
when i use curl i get this 
`curl -i http://mydomain.com/nginx_status`
`HTTP/1.1 404 Not Found
Server: nginx/1.22.0
Date: Wed, 11 Jan 2023 15:14:48 GMT
Content-Type: text/html
Content-Length: 3665
Connection: keep-alive
ETag: "63777a94-e51"

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
    <head>
        <title>The page is not found</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <style type="text/css">
            /*<![CDATA[*/
            body {
                background-color: #fff;
                color: #000;
                font-size: 0.9em;
                font-family: sans-serif,helvetica;
                margin: 0;
                padding: 0;
            }
            :link {
                color: #c00;
            }
            :visited {
                color: #c00;
            }
            a:hover {
                color: #f50;
            }
            h1 {
                text-align: center;
                margin: 0;
                padding: 0.6em 2em 0.4em;
                background-color: #294172;
                color: #fff;
                font-weight: normal;
                font-size: 1.75em;
                border-bottom: 2px solid #000;
            }
            h1 strong {
                font-weight: bold;
                font-size: 1.5em;
            }
            h2 {
                text-align: center;
                background-color: #3C6EB4;
                font-size: 1.1em;
                font-weight: bold;
                color: #fff;
                margin: 0;
                padding: 0.5em;
                border-bottom: 2px solid #294172;
            }
            h3 {
                text-align: center;
                background-color: #ff0000;
                padding: 0.5em;
                color: #fff;
            }
            hr {
                display: none;
            }
            .content {
                padding: 1em 5em;
            }
            .alert {
                border: 2px solid #000;
            }

            img {
                border: 2px solid #fff;
                padding: 2px;
                margin: 2px;
            }
            a:hover img {
                border: 2px solid #294172;
            }
            .logos {
                margin: 1em;
                text-align: center;
            }
            /*]]>*/
        </style>
    </head>

    <body>
        <h1><strong>nginx error!</strong></h1>

        <div class="content">

            <h3>The page you are looking for is not found.</h3>

            <div class="alert">
                <h2>Website Administrator</h2>
                <div class="content">
                    <p>Something has triggered missing webpage on your
                    website. This is the default 404 error page for
                    <strong>nginx</strong> that is distributed with
                    Amazon Linux 2.  It is located
                    <tt>/usr/share/nginx/html/404.html</tt></p>

                    <p>You should customize this error page for your own
                    site or edit the <tt>error_page</tt> directive in
                    the <strong>nginx</strong> configuration file
                    <tt>/etc/nginx/nginx.conf</tt>.</p>

                </div>
            </div>

            <div class="logos">
                <a href="http://nginx.net/"><img
                    src="/nginx-logo.png"
                    alt="[ Powered by nginx ]"
                    width="121" height="32" /></a>

                <a href="https://amazonlinux.com/"><img 
                    src="/poweredby.png"
                    alt="[ Powered by Amazon Linux 2 ]" 
                    width="88" height="31" /></a>
            </div>
        </div>
    </body>
</html>`

**Comment by pothi** [comment]
> Welcome to WordPress. This is your first post. Edit or delete it, then start writing!

Curl output shows correct info, with "HTTP/1.1 200 OK" header. The configuration seems to be using port 85 somewhere. Probably in WordPress site URL and home URL (`wp option get siteurl` or `wp option get home` would reveal the exact configuration in WP or visit example.com/wp-admin/options-general.php to see the URLs used). You may have used port 85 when developing the site locally and then while migrating to the live server, the port info may not have been deleted. **If** this is the reason for the errors (that you see in a browser), then please update the all URLs using a plugin, not just the site URL and home URL.

There doesn't seem to be nothing wrong with Nginx, even though I'd suggest to use the complete configuration from this repo to identify the error bit better. For example, if you use the complete configuration, you'd get 404 error as defined at https://github.com/pothi/wordpress-nginx/blob/main/errors/404.html . And, even without configuring any domain, you'd get error code 550 as defined at https://github.com/pothi/wordpress-nginx/blob/main/errors/550.html . I'd suggest to use the complete configuration and start with no domain (to make sure the [default.conf](https://github.com/pothi/wordpress-nginx/blob/main/sites-available/default.conf) works. The default.conf file doesn't depend on php either. So, it helps to identify any issue much earlier.

**Comment by noura-dev-yeh** [comment]
when i used the repo, and kept only default.conf and curl the ip address i get this:
```
curl -v http://55.18.72.134
*   Trying 55.18.72.134:80...
* connect to 55.18.72.134 port 80 failed: Connection refused
* Failed to connect to 55.18.72.134 port 80 after 0 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 55.18.72.134 port 80 after 0 ms: Connection refused
```

**Comment by noura-dev-yeh** [comment]
When i use the repo and try to access the IP address from the browser, I no longer see WordPress page, and can only see "550 - Domain is not hosted here!"
when I try to access mydomain in the browser, i get  "This site can’t be reached". 
when `curl` mydomain.com I get the 550 error. is there any other method I can debug the problem?
below is the curl result for mydomain:

```
curl -v http://mydomain.com
*   Trying 55.18.72.13:80...
* Connected to mydomain.com (55.18.72.13) port 80 (#0)
> GET / HTTP/1.1
> Host: mydomain.com
> User-Agent: curl/7.79.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 550 
< Server: nginx/1.22.0
< Date: Wed, 11 Jan 2023 17:35:49 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 229
< Connection: keep-alive
< ETag: "63beeb7c-e5"
< 
<html>
<head><title>550 Domain not hosted here</title></head>
<body bgcolor="white">
  <center><h1>550 - Domain is not hosted here!</h1><p>Probably, it is a mistake by the server administrator!</p></center>
<hr>
</body>
</html>

* Connection #0 to host mydomain.com left intact
```

**Comment by pothi** [comment]
>  when I try to access mydomain in the browser, i get "This site can’t be reached".

That's probably due to DNS cache issue within the browser (or with the OS or combination of both). I recommend Google Chrome in incognito mode to clear the cache quickly.

I see that your site initially couldn't even connect on port 80. Now, it seems to work (at least for the default.conf). The error code 550 is a first sign of success. You may put the site / vhost conf along with default.conf to make it work as well. For browser issue, please consult the browser's help pages. Usually, a browser restarts clears its internal DNS cache.

I will close this issue for now as the issue doesn't seem to be with the repo. If you see any bugs or areas of improvement, please submit a new issue. Thanks.

**Comment by noura-dev-yeh** [comment]
thank you Pothi for your amazing help
