### ISSUE TITLE
Openshift

### ISSUE THREAD

**Issue by ranib** [pothi/WordPress-Nginx#3]
Goog job on pagespeed score of perfect 100. Wonder why GTmetrix always differ http://gtmetrix.com/reports/www.tinywp.in/Ys0q4XXQ. 

Any idea how to use your repo on openshift?

**Comment by pothi** [comment]
> Wonder why GTmetrix always differ http://gtmetrix.com/reports/www.tinywp.in/Ys0q4XXQ. 

Ref: https://developers.google.com/speed/docs/insights/faq#whichpagespeed

> Any idea how to use your repo on openshift?

Sorry, no idea. You could probably help in that. Any contribution is welcome in the open source world!
