### ISSUE TITLE
No more..

### ISSUE THREAD

**Issue by jult** [pothi/wordpress-nginx#8]
`git clone git://github.com/pothi/wordpress-nginx.git $HOME/git/wordpress-nginx`
should be
`git clone https://github.com/pothi/wordpress-nginx.git $HOME/git/wordpress-nginx`

**Comment by pothi** [comment]
Thanks for the bug report. It will be fixed in the next update.

**Comment by jult** [comment]
Month later and it's still there. Guess you'd rather have people not use it?

**Comment by pothi** [comment]
Sorry about the delay to fix it. Fixed with with the commit... https://github.com/pothi/wordpress-nginx/commit/144e01498526d208bdac47f40595150f29bf794a .

Thanks for the reminder.
